---
- name: Provision k3s-cluster
  hosts: k3s-vm
  become: true
  tasks:
    - name: Remove everything but nameservers
      replace:
        path: /etc/resolv.conf
        regexp:  "^(?!nameserver).*$"
        replace: "nameserver 8.8.8.8"
    - name: update all packages
      yum:
        name: '*'
        state: latest
    - name: install k3s package
      shell: 'curl -sfL https://get.k3s.io | sh -'
      become: true

- name: copy kubeconfig
  hosts: localhost
  connection: local
  tasks:
    - name: copy kubeconfig
      copy:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
